name: Start a run from Jupyter Notebook on local server via self-hosted Github Actions runner

on:
  push:
    branches:
      - development
    paths:
      - 'notebooks/**'

jobs:
  run-notebook-in-development-environment:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
        python -m pip install kfp==1.8.14
        python -c "import kfp; print('KFP version:', kfp.__version__); print('KFP location:', kfp.__file__)"
        python -c "import kfp.dsl; print('kfp.dsl OK')"
        python -c "import kfp.v2.dsl; print('kfp.v2.dsl OK')"

        
    - name: Connect to local server and run the Notebook
      run: |       
        # Execute the Jupyter Notebook and overwrite the existing file with the results
        jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb
